from typing import Dict, Any


def generate_text_report(data: Dict[str, Any], filename: str) -> str:
    """
    Generate a clean, readable text report of the code analysis.
    """
    report = []
    
    # Header
    report.append("=" * 60)
    report.append(f"CODE ANALYSIS REPORT")
    report.append(f"File: {filename}")
    report.append("=" * 60)
    report.append("")
    
    # Summary Stats
    report.append("📊 SUMMARY")
    report.append("-" * 30)
    report.append(f"  • Imports:   {len(data.get('imports', []))}")
    report.append(f"  • Classes:   {len(data.get('classes', []))}")
    report.append(f"  • Functions: {len(data.get('functions', []))}")
    report.append(f"  • Calls:     {len(data.get('calls', []))}")
    report.append("")
    
    # Imports Section
    imports = data.get('imports', [])
    if imports:
        report.append("📥 IMPORTS")
        report.append("-" * 30)
        for imp in imports:
            if imp.get('module'):
                report.append(f"  from {imp['module']} import {imp['name']}")
            else:
                report.append(f"  import {imp['name']}")
        report.append("")
    
    # Classes Section
    classes = data.get('classes', [])
    if classes:
        report.append("📦 CLASSES")
        report.append("-" * 30)
        for cls in classes:
            bases = ', '.join(cls.get('bases', [])) or 'object'
            report.append(f"  class {cls['name']}({bases})")
            if cls.get('docstring'):
                report.append(f"    \"{cls['docstring'][:50]}...\"")
            methods = cls.get('methods', [])
            if methods:
                report.append(f"    Methods ({len(methods)}):")
                for m in methods[:5]:
                    args = ', '.join(m.get('args', []))
                    report.append(f"      - {m['name']}({args})")
                if len(methods) > 5:
                    report.append(f"      ... and {len(methods) - 5} more")
            report.append("")
    
    # Functions Section
    functions = data.get('functions', [])
    if functions:
        report.append("⚡ STANDALONE FUNCTIONS")
        report.append("-" * 30)
        for func in functions:
            args = ', '.join(func.get('args', []))
            report.append(f"  def {func['name']}({args})")
            if func.get('docstring'):
                report.append(f"    \"{func['docstring'][:50]}...\"")
        report.append("")
    
    # Call Graph Section
    calls = data.get('calls', [])
    if calls:
        report.append("🔗 FUNCTION CALLS")
        report.append("-" * 30)
        # Group by caller
        call_map = {}
        for call in calls:
            caller = call.get('caller_scope', 'global')
            callee = call.get('callee', '?')
            if caller not in call_map:
                call_map[caller] = set()
            call_map[caller].add(callee)
        
        for caller, callees in call_map.items():
            report.append(f"  {caller} calls:")
            for callee in sorted(callees):
                report.append(f"    → {callee}")
        report.append("")
    
    # Footer
    report.append("=" * 60)
    report.append("Generated by CodeScribe AI")
    report.append("=" * 60)
    
    return "\n".join(report)
